# Generated by Django 5.2.3 on 2025-06-20 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_todoitem_user_alter_todoitem_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="todoitem",
            name="time_spent",
            field=models.IntegerField(default=0),
        ),
    ]
