# Generated by Django 4.2.2 on 2023-07-06 06:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_todoitem_user_alter_todoitem_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
