# Generated by Django 3.2.25 on 2025-06-25 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_todoitem_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='completed',
        ),
    ]
