# Generated by Django 3.2.25 on 2025-06-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_todoitem_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='status',
            field=models.CharField(choices=[('todo', 'To Do'), ('inprogress', 'In Progress'), ('done', 'Done'), ('blocker', 'Blocker')], default='todo', max_length=10),
        ),
    ]
