# Generated by Django 3.2.25 on 2025-07-15 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_create_project_admin_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='estimation_time',
            field=models.IntegerField(default=0),
        ),
    ]
