# Generated by Django 3.2.25 on 2025-07-21 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_todoitem_estimation_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='task_date',
        ),
        migrations.CreateModel(
            name='TodoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_time', models.FloatField(default=0)),
                ('task_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('todo_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='users.todoitem')),
            ],
        ),
    ]
