# Generated by Django 3.2.25 on 2025-07-27 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20250721_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='estimation_time',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='time_spent',
            field=models.FloatField(default=0),
        ),
    ]
