# Generated by Django 3.2.25 on 2025-07-13 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_userprofile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_date',
        ),
    ]
