# Generated by Django 3.2.25 on 2025-07-27 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20250727_0447'),
        ('users', '0015_auto_20250727_0634'),
    ]

    operations = [
    ]
