# Generated by Django 3.2.25 on 2025-07-13 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_task_task_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasklog',
            old_name='task_date',
            new_name='log_date',
        ),
    ]
